package fr.uge.modules.api.model.entities;

import java.sql.Timestamp;
import java.util.List;
import java.util.Objects;

import io.quarkus.hibernate.reactive.panache.PanacheEntityBase;
import jakarta.persistence.Basic;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "log", schema = "public", catalog = "rootcause")
public class LogEntity extends PanacheEntityBase {
    @Id
    @Column(name = "id")
    public long id;

    @Basic
    @Column(name = "datetime")
    public Timestamp datetime;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "idlog")
    public List<TokenEntity> tokens;

    @OneToOne
    @JoinColumn(name = "id")
    public RawLogEntity rawLog;

    @Column(name = "autogeneratedDatetime")
    public boolean autogeneratedDatetime;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setTokens(List<TokenEntity> tokens) {
        this.tokens = tokens;
    }

    public Timestamp getDatetime() {
        return datetime;
    }

    public List<TokenEntity> getTokens() {
        return this.tokens;
    }

    public void setDatetime(Timestamp datetime) {
        this.datetime = datetime;
    }

    public RawLogEntity getRawLog() {
        return rawLog;
    }

    public void setRawLog(RawLogEntity rawLog) {
        this.rawLog = rawLog;
    }

    public boolean getAutogeneratedDatetime() {
        return autogeneratedDatetime;
    }

    public void setAutogeneratedDatetime(boolean autogeneratedDatetime) {
        this.autogeneratedDatetime = autogeneratedDatetime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        LogEntity logEntity = (LogEntity) o;
        return id == logEntity.id && Objects.equals(datetime, logEntity.datetime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, datetime);
    }

    @Override
    public String toString() {
        return "Log{" +
                "id=" + id +
                ", datetime=" + datetime +
                ", tokens=" + tokens +
                '}';
    }
}
